Add Bangladesh holidays
spatie/holidays pull request #21
Opened 2024-01-17 16:56 UTC by arifszn

2024-01-18 00:08 UTC, nhrrob requested changes
Left feedback for minor changes.

2024-01-18 00:08 UTC, nhrrob commented on tests/.pest/snapshots/Countries/BangladeshTest/it_can_calculate_bangladesh_holidays.snap
> +        "name": "Labour Day",
Should match with src/Countries/Bangladesh.php

2024-01-18 00:08 UTC, nhrrob commented on tests/.pest/snapshots/Countries/BangladeshTest/it_can_calculate_bangladesh_holidays.snap
> +        "name": "Christmas",
Should match with src/Countries/Bangladesh.php

2024-01-18 04:02 UTC, nhrrob approved these changes
LGTM

2024-01-18 08:11 UTC, Muhammad-Sarfaraz commented
Hey there! Noticed most of holiday names are in their mother tongue – how about a sprinkle of Bengali magic to celebrate diversity?
[https://github.com/spatie/holidays/blob/main/src/Countries/Belgium.php](url)
[https://github.com/spatie/holidays/blob/main/src/Countries/Brazil.php](url)
https://github.com/spatie/holidays/blob/main/src/Countries/Hungary.php

`'শহীদ দিবস' => '02-21',
'মুজিব জয়ন' => '03-17',
'Genocide Remembrance Day' => '03-25',
'স্বাধীনতা দিবস' => '03-26',
'ঈদুল ফিতর' => '04-10',
'পহেলা বৈশাখ' => '04-14',
'মে দিবস' => '05-01',
'বুদ্ধ পূর্ণিমা' => '05-19',
'ঈদুল আযহা' => '06-16',
'আশুরা' => '07-16',
'জাতীয় শোক দিবস' => '08-15',
'জন্মাষ্টমী' => '08-24',
'ঈদে মিলাদুন্নবী' => '09-15',
'দুর্গা পূজা' => '10-08',
'Armed Forces Day' => '11-21',
'Martyred Intellectuals Day' => '12-14',
'বিজয় দিবস' => '12-16',
'বড়দিন' => '12-25',`

2024-01-18 08:19 UTC, nhrrob commented
Dont think bangla would be a good choice here.
Also naming should match official or govt names. Ex 21 Feb. 

Only fixed dates are added here. 
So we cant add Eid holidays.

2024-01-18 09:32 UTC, Muhammad-Sarfaraz commented
> Dont think bangla would be a good choice here. Also naming should match official or govt names. Ex 21 Feb.
> 
> Only fixed dates are added here. So we cant add Eid holidays.

Got it!

2024-01-19 20:57 UTC, Nielsvanpach commented
Thanks!

2024-01-19 20:57 UTC, merged