Added Colombia Holidays
spatie/holidays pull request #55
Opened 2024-01-18 00:23 UTC by alvleont

Added the Colombia's holidays. There's a situation with some holidays due to the "Emiliany Law" they are moved to the following monday if it is not monday, so a function to deal with that was added.

2024-01-18 14:51 UTC, Nielsvanpach reviewed
Thanks! Could you rebase your branch on main, so I can run the tests here?

2024-01-18 14:51 UTC, Nielsvanpach commented on src/Countries/Colombia.php
> +    /** @return array<string, CarbonImmutable> */
You can remove this line

2024-01-18 16:57 UTC, Nielsvanpach commented
No worries. Make sure your fork is in sync with this package: 
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

You could always try a new branch from main and make a new PR

2024-01-18 18:36 UTC, alvleont commented
Done.

2024-01-19 08:02 UTC, luisprmat approved these changes
This implementation looks correct, I also tested it.

2024-01-19 15:47 UTC, Nielsvanpach commented
Could you verify if the dates are correct in the generated snapshot? At the moment the test is failing

2024-01-19 18:09 UTC, luisprmat commented
> Could you verify if the dates are correct in the generated snapshot? At the moment the test is failing

@Nielsvanpach The dates are correct, the problem seems to be with the data types for emiliani

> Could you verify if the dates are correct in the generated snapshot? At the moment the test is failing

@Nielsvanpach The dates are correct, the problem seems to be with the data types for `emilianiHoliday()` params.
If we change to
```php
private function emilianiHoliday(CarbonImmutable|null $date = null)
```
??

2024-01-19 21:32 UTC, Nielsvanpach commented
I'm not aware of the situation in Colombia. I'll leave this PR open for other Colombians to discuss

2024-01-22 22:17 UTC, alvleont commented
Ok, I did some extra reviews and it seems there was some problems with "Dia de San José" date, and also because all Emiliani dates timezone were not set. So @Nielsvanpach @luisprmat , I guess everything should work fine now.

2024-01-23 05:46 UTC, luisprmat commented
Hi @alvleont, your change of 'March 19' to 'March 20' for *"Día de san José"* may work but it is not the right thing to do. Testing with your code **I also found** an error in 2026 with the day of the "Reyes magos"; in the snapshot it is obtained on "2026-01-05" but it should be "2026-01-12". 

Reviewing I found the following problems for which I propose these solutions:

**Problem 1** - The delays of one day in some cases are due to the creation of the dates on the GitHub actions test server, since if it is very close at midnight it is created for the next day and therefore it does not match the snapshot. **Solution**: After creating the date with `CarbonImmutable` chain the `->startOfDay()` method to reset the time to *00:00:00* so I no longer see the need to use timezone.

**Problem 2** - The `phpstan` analysis fails because the data type of the method `CarbonImmutable::createFromFormat` returns an union type `CarbonImmutable|false` but the `emilianiHoliday` method expects a parameter with only `CarbonImmutable` type. **Solution**: Use the method `CarbonImmutable::createFromDate($year, $month, $day, $timezone?)`, this method returns only `CarbonImmutable` and it does not generate problems with `phpstan`.

**CONCLUSION**
This is my proposal for `src/Countries/Colombia.php`
```php
<?php

namespace Spatie\Holidays\Countries;

use Carbon\CarbonImmutable;

class Colombia extends Country
{
    public function countryCode(): string
    {
        return 'co';
    }

    protected function allHolidays(int $year): array
    {
        return array_merge([
            'Año Nuevo' => '01-01',
            'Día del Trabajo' => '05-01',
            'Día de la independencia' => '07-20',
            'Batalla de Boyacá' => '08-07',
            'Inmaculada Concepción' => '12-08',
            'Navidad' => '12-25',
        ], $this->variableHolidays($year));
    }

    /** @return array<string, CarbonImmutable> */
    protected function variableHolidays(int $year): array
    {
        $easter = $this->easter($year);

        return [
            'Reyes Magos' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 1, 6)->startOfDay()),
            'Día de San José' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 3, 19)->startOfDay()),
            'San Pedro y San Pablo' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 6, 29)->startOfDay()),
            'Asunción de la Virgen' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 8, 15)->startOfDay()),
            'Día de la raza' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 10, 12)->startOfDay()),
            'Todos los santos' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 11, 1)->startOfDay()),
            'Independencia de Cartagena' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 11, 11)->startOfDay()),
            'Jueves Santo' => $easter->subDays(3),
            'Viernes Santo' => $easter->subDays(2),
            'Ascención de Jesús' => $easter->addDays(43),
            'Corpus Christi' => $easter->addDays(64),
            'Sagrado corazón de Jesús' => $easter->addDays(71),

        ];
    }

    /** @return CarbonImmutable */
    private function emilianiHoliday(CarbonImmutable $date): CarbonImmutable
    {
        if ($date->is('Monday')) {
            return $date;
        } else {
            return $date->next('Monday');
        }
    }
}
```
I also *suggest* changing `emilianiHoliday` to something more descriptive like `movableHoliday` or something, but it's not as relevant.

2024-01-23 05:47 UTC, luisprmat requested changes
Hi @alvleont, your change of 'March 19' to 'March 20' for *"Día de san José"* may work but it is not the right thing to do. Testing with your code **I also found** an error in 2026 with the day of the "Reyes magos"; in the snapshot it is obtained on "2026-01-05" but it should be "2026-01-12". 

Reviewing I found the following problems for which I propose these solutions:

**Problem 1** - The delays of one day in some cases are due to the creation of the dates on the GitHub actions test server, since if it is very close at midnight it is created for the next day and therefore it does not match the snapshot. **Solution**: After creating the date with `CarbonImmutable` we chain the method `->startOfDay()` to reset the time to *00:00:00* so I no longer see the need to use timezone.

**Problem 2** - The `phpstan` analysis fails because the data type of the method `CarbonImmutable::createFromFormat` returns an union type `CarbonImmutable|false` but the `emilianiHoliday` method expects a parameter with only `CarbonImmutable` type. **Solution**: Use the method `CarbonImmutable::createFromDate($year, $month, $day, $timezone?)`, this method returns only `CarbonImmutable` and it does not generate problems with `phpstan`.

**CONCLUSION**
This is my proposal for `src/Countries/Colombia.php`
```php
<?php

namespace Spatie\Holidays\Countries;

use Carbon\CarbonImmutable;

class Colombia extends Country
{
    public function countryCode(): string
    {
        return 'co';
    }

    protected function allHolidays(int $year): array
    {
        return array_merge([
            'Año Nuevo' => '01-01',
            'Día del Trabajo' => '05-01',
            'Día de la independencia' => '07-20',
            'Batalla de Boyacá' => '08-07',
            'Inmaculada Concepción' => '12-08',
            'Navidad' => '12-25',
        ], $this->variableHolidays($year));
    }

    /** @return array<string, CarbonImmutable> */
    protected function variableHolidays(int $year): array
    {
        $easter = $this->easter($year);

        return [
            'Reyes Magos' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 1, 6)->startOfDay()),
            'Día de San José' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 3, 19)->startOfDay()),
            'San Pedro y San Pablo' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 6, 29)->startOfDay()),
            'Asunción de la Virgen' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 8, 15)->startOfDay()),
            'Día de la raza' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 10, 12)->startOfDay()),
            'Todos los santos' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 11, 1)->startOfDay()),
            'Independencia de Cartagena' => $this->emilianiHoliday(CarbonImmutable::createFromDate($year, 11, 11)->startOfDay()),
            'Jueves Santo' => $easter->subDays(3),
            'Viernes Santo' => $easter->subDays(2),
            'Ascención de Jesús' => $easter->addDays(43),
            'Corpus Christi' => $easter->addDays(64),
            'Sagrado corazón de Jesús' => $easter->addDays(71),

        ];
    }

    /** @return CarbonImmutable */
    private function emilianiHoliday(CarbonImmutable $date): CarbonImmutable
    {
        if ($date->is('Monday')) {
            return $date;
        } else {
            return $date->next('Monday');
        }
    }
}
```
I also *suggest* changing `emilianiHoliday` to something more descriptive like `movableHoliday` or something, but it's not as relevant.

2024-01-23 20:08 UTC, luisprmat approved these changes
Reviewing, I tested from 2016 to 2026 (in my PC, time for Colombia) and i **didn't find errors**. The code looks good and I think we should **merge** it, if an error arises later we will report it and we will resolve it.

2024-01-23 20:20 UTC, luisprmat commented
@Nielsvanpach please review!

2024-01-23 23:05 UTC, juancho48 reviewed
This is perfect! Will withdraw mine

2024-01-24 12:43 UTC, Nielsvanpach approved these changes
Thanks!

2024-01-24 12:43 UTC, merged